clear;
clc;
bmaior=0;
bmenor=0;
h=0;
st=0;
bmaior=4;
bmenor=2;
h=1.5;
st=((bmaior+bmenor)*h)/2;
fprintf('A area do trapezio eh: %d\n',st);
fprintf('----------------------\n');
fprintf('fim do programa\n');